### ISSUE TITLE
[Suggestion] Spawn at the team home location when die

### ISSUE THREAD

**Issue by Baktus79** [Misat11/BedWars#1]
Hey, must say this plugin works awesome :D Very good job on this plugin!

**Suggestion**
Could you make it so that when a player die, they respawn at the player base/home instead of worldspawn?

**Comment by Baktus79** [comment]
hmm, strange. When players die they respawn at the worldspawn. 

---

**Plugins**
BedWars, BungeeTabListPlus, Citizens, CMI, CoreProtect, Denizen, Depenizen, Lottery, LuckPerms, MinePacks, MobArena, Multiverse-Core, PlaceholderAPI, PlotSquared, PlugMan, PreventPortBypass, ProtocolLib, SelectionVisualizer, Vault, WorldEdit, WorldGuard, WorldGuardExtraFlags

**BedWars version:** 0.0.5
**Server type:** Paper
**Server version:** git-Paper-509 (MC: 1.13.2)

**Comment by Misat11** [comment]
OK, try to use pre-release version 0.0.6-pre3 on my jenkins server (in README). I changed event priority as it was in BedwarsRel so now it maybe can work.

**Comment by Baktus79** [comment]
Thanks :D That solved the problem!
