### ISSUE TITLE
Set block amount not being bought

### ISSUE THREAD

**Issue by FleeingChickens** [Misat11/BedWars#10]
**Describe the bug**
When blocks are bought (wool in this case) instead of giving 16 like it is set to, it only gives 4 wool, sometimes 2, or even 1. It does not change every time the item is bought it changes at some random point in the game and requires the plugin to be reloaded to be fixed
**Server and plugin version**
Spigot version:
mc 1.13.2, craftbukkit version git-spigot-5629554-4c8327f, implementing api thing 1.13.2-R0.1-SNAPSHOT (i did the /version command and that is what came up)
BedWars version:
0.0.9
**Installed plugins on server (can be obtained by `/pl`):**
WorldEdit, OldCombatMechanics, PermissionsEx, Vault, ProtocolLib, WorldGuard, Multiverse-Core, LibsDisguises, Citizens, Sentinel, MythicMobs, Quests, Essesntials, Multiverse-Inventories, BedWars, Parkour, Paintball, CommandNPC, BossShop, Multiverse-Portals, HolographicDisplays, MythicArtifacts, Skywars
**Console log:**
I don't know if anything was in the console and i didn't think to check at the time of the bug
**Configuration (of config.yml and shop.yml):**

[Configs.zip](https://github.com/Misat11/BedWars/files/3100877/Configs.zip)

**If there are problem with only one game, paste here config of this game:**

**Comment by Misat11** [comment]
Can you paste valid configs? Configs.zip is empty.

**Comment by FleeingChickens** [comment]
I did change the wool amount from 16 like i said in the original post to 2 because I thought since the sandstone default block was 2 for 1 bronze it maybe wouldn't glitch but i did a game with my friend with these configs and it was still happening 




Shop:
shop-items:

#  examplecategory:
#    name: "Example category"
#    item: "GOLDEN_APPLE"
#    lore:
#    - "This is my category!"
#    - "Please buy things inside!"
#    items:
#    - price: 50
#      price-type: "bronze"
#      stack:
#        ==: org.bukkit.inventory.ItemStack
#        v: 1519
#        type: DIAMOND_SWORD
#        amount: 1
#        meta:
#          ==: ItemMeta
#          meta-type: UNSPECIFIC
#          enchants:
#            DAMAGE_ALL: 2
#          repair-cost: 1
#          Damage: 99

  armor:
    name: "Armor"
    item: DIAMOND_CHESTPLATE     
    lore:
    - "Protect yourself with armor! Click here."
    items:
    - price: 1
      price-type: bronze
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: LEATHER_HELMET
        amount: 1
    - price: 1
      price-type: bronze
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: LEATHER_LEGGINGS
        amount: 1
    - price: 1
      price-type: bronze
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: LEATHER_BOOTS
        amount: 1
    - price: 1
      price-type: bronze
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: LEATHER_CHESTPLATE
        amount: 1
    - price: 1
      price-type: iron
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: IRON_HELMET
        amount: 1
    - price: 2
      price-type: iron
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: IRON_CHESTPLATE
        amount: 1
    - price: 2
      price-type: iron
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: IRON_LEGGINGS
        amount: 1
    - price: 1
      price-type: iron
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: IRON_BOOTS
        amount: 1
    - price: 1
      price-type: diamond
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: LEATHER_CHESTPLATE
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 2
    - price: 1
      price-type: diamond
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: LEATHER_LEGGINGS
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 2
    - price: 1
      price-type: diamond
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: LEATHER_BOOTS
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 2
    - price: 1
      price-type: diamond
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: LEATHER_HELMET
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 2
    - price: 2
      price-type: diamond
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: IRON_HELMET
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 2
    - price: 3
      price-type: diamond
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: IRON_CHESTPLATE
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 2
    - price: 3
      price-type: diamond
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: IRON_LEGGINGS
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 2
    - price: 2
      price-type: diamond
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: IRON_BOOTS
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 2
    - price: 2
      price-type: gold
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: DIAMOND_HELMET
        amount: 1
    - price: 3
      price-type: gold
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: DIAMOND_CHESTPLATE
        amount: 1
    - price: 3
      price-type: gold
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: DIAMOND_LEGGINGS
        amount: 1
    - price: 2
      price-type: gold
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: DIAMOND_BOOTS
        amount: 1
    - price: 5
      price-type: diamond
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: DIAMOND_HELMET
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 2
    - price: 6
      price-type: diamond
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: DIAMOND_CHESTPLATE
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 2
    - price: 6
      price-type: diamond
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: DIAMOND_LEGGINGS
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 2
    - price: 5
      price-type: diamond
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: DIAMOND_BOOTS
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 2
  
  swords:
    name: "Swords"
    item: DIAMOND_SWORD     
    lore:
    - "Click here to get sword for attacking your enemies"
    items:
    - price: 8
      price-type: bronze
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: STICK
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            KNOCKBACK: 1
    - price: 1
      price-type: bronze
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: WOODEN_SWORD 
        amount: 1
    - price: 10
      price-type: bronze
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: STONE_SWORD  
        amount: 1
    - price: 7
      price-type: iron
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: IRON_SWORD 
        amount: 1
    - price: 4
      price-type: gold
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: DIAMOND_SWORD  
        amount: 1
    - price: 2
      price-type: diamond
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: WOODEN_SWORD
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            DAMAGE_ALL: 1
    - price: 4
      price-type: diamond
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: STONE_SWORD
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            DAMAGE_ALL: 1
    - price: 5
      price-type: diamond
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: IRON_SWORD
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            DAMAGE_ALL: 1
    - price: 6
      price-type: diamond
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: DIAMOND_SWORD
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            DAMAGE_ALL: 1
    
  bows:
    name: "Bows"
    item: BOW     
    lore:
    - "Prove yourself as a marksman with these wonderful bows"
    items:
    - price: 5
      price-type: iron
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: BOW
        amount: 1
    - price: 1
      price-type: iron
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: ARROW
        amount: 1 
  eat:
    name: "Eat"
    item: COOKED_PORKCHOP     
    lore:
    - "Are you hungry? Get something to eat."
    items:
    - price: 4
      price-type: bronze
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: COOKED_PORKCHOP
        amount: 2
    - price: 2
      price-type: iron
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: GOLDEN_APPLE
        amount: 1
    - price: 5
      price-type: gold
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: BREAD
        amount: 10
        
  pickaxes:
    name: "Pickaxes"
    item: DIAMOND_PICKAXE     
    lore:
    - "Destroy others blocks? Use these pickaxes."
    items:
    - price: 10
      price-type: bronze
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: WOODEN_PICKAXE
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            DIG_SPEED: 1
    - price: 20
      price-type: bronze
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: STONE_PICKAXE
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            DIG_SPEED: 2
    - price: 4
      price-type: iron
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: IRON_PICKAXE
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            DIG_SPEED: 3
    - price: 5
      price-type: gold
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: DIAMOND_PICKAXE
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            DIG_SPEED: 3
            
  blocks:
    name: "Blocks"
    item: WHITE_WOOL   
    lore:
    - "Destroy others blocks? Use these pickaxes."
    items:
    - price: 1
      price-type: bronze
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: WHITE_WOOL
        amount: 2
    - price: 24
      price-type: bronze
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: END_STONE
        amount: 12
    - price: 4
      price-type: iron
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: OAK_PLANKS
        amount: 16
    - price: 4
      price-type: gold
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: OBSIDIAN
        amount: 4
            
  usefulstuff:
    name: "Useful Stuff"
    item: TNT     
    lore:
    - "Looking for useful stuff? Here are some!"
    items:
    - price: 1
      price-type: iron
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: CHEST
    - price: 1
      price-type: gold
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: ENDER_CHEST
    - price: 50
      price-type: bronze
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: FIRE_CHARGE
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: "§cFireball"
          lore:
          - "§7Right-Click to Shoot a Fireball"
    - price: 7
      price-type: iron
      properties:
      - name: "WarpPowder"
        delay: 6
      stack:
        ==: org.bukkit.inventory.ItemStack
        type: GUNPOWDER
        v: 1519
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: "Warp Powder"
          lore:
          - "When using this powder you'll get"
          - "teleported to you spawn point within 6 seconds"
          - "Warning: Any movement will stop the process"
        
              
  
              
          
          
          

Config:
# Locale (en, cs, ru)
locale: en

allow-crafting: false
keep-inventory-on-death: false
in-lobby-colored-leather-by-team: true
jointeam-entity-show-name: true
friendlyfire: false
player-drops: true
join-randomly-after-lobby-timeout: false
spectator-gm3: false
prevent-killing-villagers: true
compass-enabled: true
join-randomly-on-lobby-join: true
add-wool-to-inventory-on-join: true

# Commands whitelist
allowed-commands:
- "/help"
- "/shop RedShop"
- "/shop BlueShop"
- "/shop GreenShop"
- "/shop YellowShop"

# Ignored blocks (Farm blocks)
farmBlocks:
  enable: true
  blocks:
  - WHEAT
  - CARROTS
  - POTATOES
  - BEETROOTS

# Scoreboard settings
scoreboard:
  enable: true
  title: "§a%game%§r - %time%"
  bedLost: "§c\u2718"
  bedExists: "§a\u2714"
  teamTitle: "%bed%%color%%team%"
  
# Title speed
title:
  fadeIn: 0
  stay: 20
  fadeOut: 0
  
# Items
items:
  jointeam: COMPASS
  leavegame: SLIME_BALL
  shopback: BARRIER
  shopcosmetic: GRAY_STAINED_GLASS_PANE
  pageback: ARROW
  pageforward: ARROW
  
# Vault rewards
vault:
  enable: false
  reward:
    kill: 5
    win: 20
  
# Resources
resources:
  bronze:
    material: IRON_INGOT
    interval: 2
    name: "Iron"
    translate: "resource_iron"
    color: GRAY
    spread: 1.0
  iron:
    material: GOLD_INGOT
    interval: 8
    name: "Gold"
    translate: "resource_gold"
    color: GOLD
    spread: 1.0
  gold:
    material: EMERALD
    interval: 40
    name: "Emerald"
    translate: "resource_emerald"
    color: GREEN
    spread: 1.0
  diamond:
    material: DIAMOND
    interval: 20
    name: "Diamond"
    translate: "resource_diamond"
    color: AQUA
    spread: 1.0
    
# Sounds (look to github src/main/java/misat11/bw/utils/Sounds.java for possible values)
sounds:
  on_bed_destroyed: ENTITY_ENDER_DRAGON_GROWL
  on_countdown: UI_BUTTON_CLICK
  on_game_start: ENTITY_PLAYER_LEVELUP
  on_team_kill: ENTITY_PLAYER_LEVELUP
  on_item_buy: ENTITY_ITEM_PICKUP
  
# Game effects
game-effects:
  end: 
    type: Firework
    power: 1
    effects:
    - ==: org.bukkit.FireworkEffect
      type: BALL
      fade-colors:
      - ==: org.bukkit.Color
        RED: 255
        GREEN: 255
        BLUE: 255
      colors:
      - ==: org.bukkit.Color
        RED: 255
        GREEN: 255
        BLUE: 255
      trail: false
      flicker: false
  start: {}
  kill: {}
  teamkill: {}
  lobbyjoin: {}
  lobbyleave: {}
  respawn: {}
  beddestroy: {}
  warppowdertick: {}
  
  
# Lobby scoreboard
lobby-scoreboard:
  enabled: true

  title: "§eBEDWARS"
  
  content:
    - " "
    - "§fMap: §2%arena%"
    - "§fPlayers: §2%players%§f/§2%maxplayers%"
    - " "
    - "§fWaiting ..."
    - " "
  
# Statistics  
statistics:
  enabled: true
  type: 'yaml'
  show-on-game-end: true
  bed-destroyed-kills: false
  
  # Scores configuration
  scores:
    kill: 10
    die: 0
    win: 50
    bed-destroy: 25
    lose: 0
    record: 100
  
# database (currently only mysql) configuration
database:
  host: localhost
  port: 3306
  db: database
  user: root
  password: secret
  table-prefix: bw_
  
# Do not edit this!!!
version: 2

**Comment by Misat11** [comment]
@FleeingChickens your config is valid and working, you can try on localhost start server only with world and bedwars plugin with configuration. Maybe there is a plugin that breaks this.

**Comment by Chicken009** [comment]
From my experience the plugin Multiverse-Inventories does not work very well with bedwars. Try disabling it and look if the error still occurs
