### ISSUE TITLE
People without server op cant build in the middle of the map 

### ISSUE THREAD

**Issue by Jerryqtt** [Misat11/BedWars#12]
Hi, on my server people without op permissons cant build from the middle of the map on the server is on 1.14 everything is running perfect. I first toguht i might have placed the pos1 and 2 wrong but after some testing had to find out that everyone need op to build. Is there a permisson that i can define in pex or lp?

**Comment by Misat11** [comment]
Just move world spawn out of arena or disable spawn protection in server.properties.

**Comment by Jerryqtt** [comment]
thanks for your fast answer :) it worked but i have one more problem, when i try to add a holo it says holo is disabled is there a way to fix?

**Comment by Misat11** [comment]
Have you installed HolographicDisplays? Now it's needed for creating multiline holograms.

**Comment by Jerryqtt** [comment]
no i haven`t ill try this but i never spawned any holograms on my server

**Comment by Jerryqtt** [comment]
okay so the holograms plugin doesnt work for 1.14 :/

**Comment by Misat11** [comment]
Try to use development build of HolographicDisplays https://ci.filoghost.me/job/HolographicDisplays/
