### ISSUE TITLE
A bunch of requests

### ISSUE THREAD

**Issue by Chicken009** [Misat11/BedWars#13]
1: When there is the ability to fall into the void while in the lobby you will just fall on forever and if you 
   then leave the lobby you will die from falldamage. Players should be teleported back to the Lobby 
   spawn as soon as they enter the void and they should (maybe also) dont receive falldamage when 
   leaving the lobby.

2: Is it possible to buy whole stacks of items when shift clicking in the shop?

3: Commands to edit the shop from ingame?

4: I want to translate the plugin

5: It would also be cool to have an option for bwrewritten to automatically place spawners on 
   gold/ironblocks etc. It would look like this: automatically-place-itemspawners: false (dafault)

6: Make an option to have no mobs spawning in the lobby

7: fix prefixes from bedwars overwriting other prefixes

**Comment by Misat11** [comment]
@Chicken009

1, 2, 6: I' ll add it.

3: Do you mean editing of .yml file? It could be complicated to work with it, but I try to do this in some future version.

4: Look at spigot page, there is tutorial, how translate this plugin. If you want to add translate to new version, make pull request.

5: It could be good, I'll try to do this.

7: How do you mean this? Can you explain it?

**Comment by Chicken009** [comment]
3: It was just an idea I had but its not that important

4: I meant translating for a new version (to german)

7: I use permissionex´s prefixes for the chat and namtagedit´s prefixes for the scoreboard, ingame only the bedwars nametags are shown in the scoreboard and in the chat there are only the pex prefixes. How do I fix this or make it so that there is the pex prefix and the name is shown in the teams color?

**Comment by Misat11** [comment]
4: So you can create new `messages_de.yml` and make pull request with this file. (I wanted to do it but I don't speak German very welll.)

7: This plugin just add you into team that has color or in legacy versions color prefix. This plugin is not editing chat, tablist or scoreboard (if you has own). It could be new option in future.

**Comment by Chicken009** [comment]
So where can I find the messages_en.yml so i can switch all of them out?

**Comment by Misat11** [comment]
1: 2b3c28dc3cdff9dafc1e321f4384075ac7f1f89d

**Comment by Misat11** [comment]
2: e114bc5bc72ac128f5c922dd514ba60f0a7e1a3c added
Features 1 and 2 are available in 0.1.1

**Comment by Misat11** [comment]
6: 968944a02f80245db26274917fcb96456e718cf2 added

**Comment by Misat11** [comment]
6: f3d363a43298ff45fb23f1affbf2114c19102c13 added
