### ISSUE TITLE
Command reward per win/kill

### ISSUE THREAD

**Issue by artemati1** [Misat11/BedWars#16]
I would like this plugin to have the opportunity to reward the player for winning / killing not a currency, but a team. I need a player to give 1 mystery box for a player, can this be done without updates? 
*Google translator*

**Comment by Misat11** [comment]
7ca583a3c71f9a25a7e0c9cb6e07581a2226849c Available now at development build of Bedwars 0.1.2. There are four events: player-win, player-kill, player-bed-destroy and player-end-game. Win and endgame is running after game ends. And there are two placeholders `{player}` and `{score}`.
