### ISSUE TITLE
Shop won't work, on 1.14.1

### ISSUE THREAD

**Issue by John649** [Misat11/BedWars#17]
**Describe the bug**

**Server and plugin version**
Spigot version:
BedWars version:

**Installed plugins on server (can be obtained by `/pl`):**

**Console log:**

**Configuration (of config.yml and shop.yml):**

**If there are problem with only one game, paste here config of this game:**

**Comment by John649** [comment]
Update: I found a fix but I found a new issue, When I restarted my server, the game was disabled, and when i tried to save, it told me to edit, and when i went to edit mode, it said there was an internal error. Please help, I tried restarting the server, reloading the plugin, but nothing works.

**Comment by John649** [comment]
I was on spigot version.

**Comment by John649** [comment]
Update: Now I can't save.

**Comment by Misat11** [comment]
Please use bug issue template and send me all informations.

**Comment by John649** [comment]
What's a console log?

**Comment by John649** [comment]
Bug already described

Spigot version

![image](https://user-images.githubusercontent.com/50850010/58374937-1b90e700-7f16-11e9-8d53-6531becbaa27.png)

I am using minehut so i DO not have access to console log

Config: https://pastebin.com/hwR3d2eu

Shop.yml : https://pastebin.com/maDLz3Mw

**Comment by Misat11** [comment]
What is Spigot version? I need
Spigot version: use /version and paste here output: git-Spigot-........ (MC 1.××)
and Bedwars version: for example 0.1.1

And console log you can find at logs/latest.log or logs/date.log.gz or just open console/terminal when your server is running, find errors related with Bedwars and send me it.

**Comment by John649** [comment]
> What is Spigot version? The latest one, I’m not sure what though,
> Spigot version: use /version and paste here output: git-Spigot-........ (MC 1.××)
> and Bedwars version: for example 0.1.1 <that is the bedwars version
> 
> And console log you can find at logs/latest.log or logs/date.log.gz or just open console/terminal when your server is running, find errors related with Bedwars and send me it.   >Minehut does not have a console log, and my server runs on it

**Comment by Misat11** [comment]
If you can't find something like this:

> [15:48:49] [Server thread/ERROR]: Could not pass event InventoryClickEvent to BedWars v0.1.2-pre1
> org.bukkit.event.EventException: null
> 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.14.1.jar:git-Spigot-8043ebc-02b466c]
> 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.14.1.jar:git-Spigot-8043ebc-02b466c]
> 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) ~[spigot-1.14.1.jar:git-Spigot-8043ebc-02b466c]
> 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:505) ~[spigot-1.14.1.jar:git-Spigot-8043ebc-02b466c]
> 	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2158) ~[spigot-1.14.1.jar:git-Spigot-8043ebc-02b466c]
> 	at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[spigot-1.14.1.jar:git-Spigot-8043ebc-02b466c]
> 	at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[spigot-1.14.1.jar:git-Spigot-8043ebc-02b466c]
> 	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13) ~[spigot-1.14.1.jar:git-Spigot-8043ebc-02b466c]
> 	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.14.1.jar:git-Spigot-8043ebc-02b466c]
> 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [spigot-1.14.1.jar:git-Spigot-8043ebc-02b466c]
> 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.14.1.jar:git-Spigot-8043ebc-02b466c]
> 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [spigot-1.14.1.jar:git-Spigot-8043ebc-02b466c]
> 	at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:895) [spigot-1.14.1.jar:git-Spigot-8043ebc-02b466c]
> 	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:888) [spigot-1.14.1.jar:git-Spigot-8043ebc-02b466c]
> 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:123) [spigot-1.14.1.jar:git-Spigot-8043ebc-02b466c]
> 	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:872) [spigot-1.14.1.jar:git-Spigot-8043ebc-02b466c]
> 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:805) [spigot-1.14.1.jar:git-Spigot-8043ebc-02b466c]
> 	at java.lang.Thread.run(Thread.java:835) [?:?]

I can't help you.

**Comment by John649** [comment]
Hey, I found the logs.

https://pastebin.com/9ntLYESq

Here, please let me know with the problem and try to send me a new thing.

**Comment by Misat11** [comment]
/bw admin `<arena>` edit - <arena> in brackets means, that here will be name of your arena, for example arena1. And before editting you must add it
/bw admin `arena1` add
/bw admin `arena1` save

**Comment by John649** [comment]
I know, <arena> is the name of the arena

**Comment by John649** [comment]
Also, what is your socials, I would like to contact you easier.

**Comment by Misat11** [comment]
If you look into the log, you can see user using command /bw admin <arena> edit, not /bw admin `somearenaname` edit

I'll create new discord server and paste link into spigotmc bedwars page.

**Comment by John649** [comment]
Please give me your discord though, its hard doing this back and fourth.

**Comment by Misat11** [comment]
https://discord.gg/VgrFUbV
