### ISSUE TITLE
[Bug] Scoreboard display teams that are not there

### ISSUE THREAD

**Issue by Baktus79** [Misat11/BedWars#2]
The scoreboard display teams that are not playing. Seems like it display teams that where playing in the last run. See the image below

![image](https://user-images.githubusercontent.com/19745447/52015282-ee8d7400-24e1-11e9-9643-3eb3f1f0f9e1.png)
Team yellow is not playing in this round.

**Comment by Misat11** [comment]
Fixed in version 0.0.6 release - a127194

**Comment by Baktus79** [comment]
Perfect :D Thank you very much!
