### ISSUE TITLE
German - Translation

### ISSUE THREAD

**Issue by qirin23** [Misat11/BedWars#21]
**Describe the bug**
The translation contains mass spelling mistakes or bad grammar.
Please let someone create a new translation.
You are welcome to send me the messages and I translated them because I am a native German speaker.
**Server and plugin version**
Spigot version: 1.8 latest
BedWars version: latest

**Installed plugins on server (can be obtained by `/pl`):**
yes
**Console log:**
none
**Configuration (of config.yml and shop.yml):**

**If there are problem with only one game, paste here config of this game:**

**Comment by qirin23** [comment]
best regards qirin

**Comment by Misat11** [comment]
Messages are in plugin/src/main/resources and if you think that this translates is not correct, make a pull request with update. Current translates are from another user because I don't speak German very well so I can't fix this mistakes.

**Comment by iamceph** [comment]
@qirin23 Are you going to translate German language? Please hit us up here.
