### ISSUE TITLE
Some requests

### ISSUE THREAD

**Issue by Boy132** [Misat11/BedWars#23]
- make some "premium" commands (force start, maybe force join team?)
- make a config for the sign layout
- auto assign a team to players that havn't picked one when the min players are reached

Also please let the console run the "bw reload" command.

**Comment by Misat11** [comment]
1) I add it into TODO list.
2) Sign layout is editable in messages config, look into spigot page, how to modify messages/translates.
3) There is already this option look into configuration.

**Comment by Boy132** [comment]
You can't change the sign layout, you can only translate the text.
For example I want the "sign header" to be a colored text and the arena on the 4th line.
