### ISSUE TITLE
holo-countdown

### ISSUE THREAD

**Issue by FoviOX** [Misat11/BedWars#27]
**Description**
When I use command /bw leave, and ender to map, starting bugs and errors.
(Click on image to see video)
<div align="left">
  <a href="https://www.youtube.com/watch?v=dgw8dJ6uV4w"><img src="https://img.youtube.com/vi/dgw8dJ6uV4w/0.jpg" alt="Click to see video"></a>
</div>

![2019-07-03_15 02 55](https://user-images.githubusercontent.com/33469628/60593262-0c217b00-9dab-11e9-89d2-5269e7796a42.png)

**Server and plugin version**
Spigot version: 1.12.1
BedWars version: 0.1.5

**Log**
This error appearing when game started. And when game ended this error stops appearing.
![Screenshot_42](https://user-images.githubusercontent.com/33469628/60591282-d1b5df00-9da6-11e9-8b68-8550f7ac8ed9.jpg)

**Configuration (of config.yml and shop.yml):**
[config.yml shop.yml arenaconfig.yml.zip](https://github.com/Misat11/BedWars/files/3354882/config.yml.shop.yml.arenaconfig.yml.zip)

**Comment by Misat11** [comment]
Please find console log in logs, not print screen console there is some information about error (for me important) missing

**Comment by FoviOX** [comment]
> Please find console log in logs, not print screen console there is some information about error (for me important) missing

Here full day log: 
[2019-07-03-3.log.gz](https://github.com/Misat11/BedWars/files/3356637/2019-07-03-3.log.gz)

Here full error:
https://pastebin.com/eCPRrjhf
![image](https://user-images.githubusercontent.com/33469628/60620894-0e083000-9de5-11e9-83b7-be611e5e200c.png)

**Comment by Misat11** [comment]
This error is not related with villagers, you just have enabled spawner holo countdown and disabled normal spawner holo, that is needes for countdown now. Try to disable spawner holo countdown.

**Comment by FoviOX** [comment]
> This error is not related with villagers, you just have enabled spawner holo countdown and disabled normal spawner holo, that is needes for countdown now. Try to disable spawner holo countdown.

Ok, I understood. Maybe write message "Disable holo-countdown, because resourse holo disabled." instead error?
