### ISSUE TITLE
Don't Know About Enchantment Trident and Crossbow

### ISSUE THREAD

**Issue by Windows10-YT** [Misat11/BedWars#29]
I wanted to add enchantment Trident and crossbow and other things, but I don’t know what to write, minecraft wiki doesn’t fit
`        v: 1519
        type: trident
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            loyalty: 1
            unbreaking: 1`

**Comment by Misat11** [comment]
here is all spigot enchants: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/enchantments/Enchantment.html
