### ISSUE TITLE
[Bug] Cannot save arena

### ISSUE THREAD

**Issue by Baktus79** [Misat11/BedWars#3]
With the new update I cannot save the arena. It says "Before saving game please add at least 1 spawner!". I have already set spawners around the arena. See the image below.

![image](https://user-images.githubusercontent.com/19745447/52079825-bb58ec80-2596-11e9-9b1c-fdfb7e15378a.png)

I also tried to reset the spawners and try again, but with no luck.

---

**Plugins:**
BedWars, BungeeTabListPlus, Citizens, CMI, Denizen, Depenizen, LuckPerms, MinePacks, MobArena, Multiverse-Core, PlaceholderAPI, PlotSquared, PlugMan, PreventPortBypass, ProtocolLib, SelectionVisualizer, Vault, WorldEdit, WorldGuard, WorldGuardExtraFlags

**Bedwars plugin version:** 0.0.6
**Server type:** Paper
**Server version:** git-Paper-511 (MC: 1.13.2)

**Comment by Misat11** [comment]
Is there any error in console? What if you create new arena? I'll fix it tomorrow, now I don't have time.

**Comment by Misat11** [comment]
Try to use latest jenkins build. The problem was that I accidentally deleted one line.
