### ISSUE TITLE
message 'null' + the message is the same both

### ISSUE THREAD

**Issue by Windows10-YT** [Misat11/BedWars#31]
language RU
When killing players message 'null' + when the bed breaks the message is the same both
![bug](https://user-images.githubusercontent.com/52487964/60685465-aa513600-9ebc-11e9-8faf-975aeae089a0.PNG)
![bug3](https://user-images.githubusercontent.com/52487964/60685647-a7a31080-9ebd-11e9-8242-8402caa041fd.PNG)

**Comment by Windows10-YT** [comment]
I switched the text to English, it was different, I tried to find that text, but N ++ said that it could not find the text https://drive.google.com/file/d/1RhIDObXqHMg1I-JuiEPWAslg1Mp-g52z/view?usp=sharing

**Comment by Misat11** [comment]
I'm not editing death messages, I'm just adding prefix before it.

**Comment by Windows10-YT** [comment]
And how to edit death messages?

**Comment by Misat11** [comment]
by other plugin

**Comment by Windows10-YT** [comment]
There is no analogue of BedWars either they are paid or do not support 1.14.x

**Comment by Misat11** [comment]
I mean plugin for managing death messages, because (as I say) MY PLUGIN DO NOTHING WITH DEATH MESSAGES JUST ADDING PREFIX [BW]

**Comment by Windows10-YT** [comment]
I did not find such a plugin, I do not use BungeeCord

**Comment by jakubg1** [comment]
Custom death messages will appear in 0.2.0.
One of the developers committed the change: https://github.com/Misat11/BedWars/commit/8a348508bbdf8be72bbc1bcfd012a24ff0cdeca2

**Comment by iamceph** [comment]
This issue should be fixed in 0.2.0, please try out Jenkins build and hit me up here.

**Comment by Windows10-YT** [comment]
How ?, I'm not a programmer

**Comment by Misat11** [comment]
Link to jenkins is in README.md (button build|passing) and download file BedWars-0.2.0.jar.

**Comment by iamceph** [comment]
https://jenkins.mtorus.cz/job/BedWars/165/artifact/plugin/target/BedWars-0.2.0-SNAPSHOT.jar
