### ISSUE TITLE
Weird Holograms

### ISSUE THREAD

**Issue by JeffRabbitYT** [Misat11/BedWars#34]
Hologram combines the stats of all players present instead of just Yours.
When the server starts and it's just me, Holo looks fine. But, when someone else logs on, the hologram doubles up

Spigot version: I dunno
BedWars version: Latest

Plugin list:
    Ultimate_vote, BukkitCore, Worldedit, OldCombatMechanics
TitleWelcomeMessage, UReport, Playerserver, PermissionsEx
Chatcontrol, Antibot, StaffChatReloaded, Vault, WorldGuard
ProtocolLib, Multiverse-Core, Essentials, EssentialsChat
HolographicDisplays, Killermoney, Multiverse-Portals
BuycraftX, EssentialsSpawn, Bedwars

**Comment by Misat11** [comment]
What's your Spigot/CraftBukkit/Minecraft version (can be obtained by /version, please send me full output of this command).

And what's your HolographicDisplays version?

**Comment by JeffRabbitYT** [comment]
git-spigot-595711b-e8b39d4 (MC: 1.14.3) (Implementing API version
1.14.3-R0.1-SNAPSHOT)
You are 25 versions behind

Holographic Displays v2.3.3-SNAPSHOT by filoghost

**Comment by iamceph** [comment]
Any news on this? Did you tried latest developement build?

**Comment by JeffRabbitYT** [comment]
I don't know what that is, I just gave up. ¯\_(ツ)_/¯
