### ISSUE TITLE
Randomly stops

### ISSUE THREAD

**Issue by JeffRabbitYT** [Misat11/BedWars#35]
Game will stop while people are still playing, multiple beds still intact, it just ends itself, with no output to the LOG.

1.14.3 server

Spigot version: git-spigot-9a643a6-eb2e657
BedWars version: 0.1.6

Bukkitcore, worldedit, oldcombat, permissionsEx, chatcontrol, vault, worldguard, protocolLib, multiverseCORE, essentials, Ess.CHAt, Matrix, holo-displays, killermoney multiverse-protals, buycraftX, ess.spawn, bedwars

Nothing was output besides Chat and a cmd block, so I fell it'd be redundant,

**Configuration (of config.yml and shop.yml):**
https://gist.github.com/JeffRabbitYT/e44e858c8ec4d56c0528ccce8774f407
https://gist.github.com/JeffRabbitYT/e44e858c8ec4d56c0528ccce8774f407#gistcomment-2973306
 very annoying,

**Comment by Misat11** [comment]
can you send me config of your arena?

**Comment by JeffRabbitYT** [comment]
Sorry, a realized what was wrong when I noticed a timer on the side. Turns
out this arena had a 300 second game timer instead of 3600. It's fixed now,
thank you!
