### ISSUE TITLE
Your shop.yml/shop.groovy is wrong! Loading default one instead

### ISSUE THREAD

**Issue by ShinkaiPH** [Misat11/BedWars#381]
#### Describe the bug
After I reloaded the plugins, I got the message in my logs that I could not load my new shop.YML and it continues to load the default one.

#### Server and plugin version
Spigot version: LATEST
BedWars version: LATEST

#### CONSOLE LOG

[Thu, 28. Oct 2021 03:34:12 UTC INFO] ShinkaiPH issued server command: /bw reload
[Thu, 28. Oct 2021 03:34:12 UTC INFO] Disabling BedWars v0.2.20
[Thu, 28. Oct 2021 03:34:12 UTC INFO] Unregistered placeholder expansion: bedwars
[Thu, 28. Oct 2021 03:34:12 UTC INFO] Enabling BedWars v0.2.20
[Thu, 28. Oct 2021 03:34:12 UTC INFO] Successfully loaded messages for BedWars! Language: English
[Thu, 28. Oct 2021 03:34:12 UTC INFO] Loading statistics from YAML-File ...
[Thu, 28. Oct 2021 03:34:12 UTC INFO] Successfully registered expansion: bedwars
[Thu, 28. Oct 2021 03:34:12 UTC WARN] Your shop.yml/shop.groovy is wrong! Loading default one instead
[Thu, 28. Oct 2021 03:34:12 UTC INFO] =====================  by ScreamingSandals <Misat11, Iamceph, Pronze>
[Thu, 28. Oct 2021 03:34:12 UTC INFO] + Screaming BedWars +  Version: 0.2.20 FREE
[Thu, 28. Oct 2021 03:34:12 UTC INFO] =====================  STABLE VERSION
[Thu, 28. Oct 2021 03:34:12 UTC INFO] [BW] Found Vault
[Thu, 28. Oct 2021 03:34:12 UTC INFO] [BW] Arena bw1 loaded!
[Thu, 28. Oct 2021 03:34:12 UTC INFO] [BW] Arena bw loaded!
[Thu, 28. Oct 2021 03:34:12 UTC INFO] Everything is loaded! If you like our work, consider visiting our Patreon! <3
[Thu, 28. Oct 2021 03:34:12 UTC INFO] https://www.patreon.com/screamingsandal

#### THE FILES
[shop.txt](https://github.com/ScreamingSandals/BedWars/files/7430913/shop.txt)
[config.txt](https://github.com/ScreamingSandals/BedWars/files/7430914/config.txt)

**Comment by fear-j01** [comment]
how did u fix
