### ISSUE TITLE
[Suggestion] Spectate mode should be gamemode spectate

### ISSUE THREAD

**Issue by Baktus79** [Misat11/BedWars#4]
When someone die after their bed got destroyed, they will spawn in spectate mode. But they spawn as a visible player that can push other players and still help the team. Could they be in gamemode spectate instead so that they will be invisible and that they cant touch anything?

**Comment by Misat11** [comment]
I added this option to the config in last pre release build (available on Jenkins). But this build maybe contains lot of bugs it's not tested yet.

**Comment by Baktus79** [comment]
Awesome :)
