### ISSUE TITLE
「TODO」translate  to Chinese

### ISSUE THREAD

**Issue by WangYneos** [Misat11/BedWars#42]
HI, i am happy to see that your plugin support Minecraft 1.14
However your plugin do not support Chinese.
So , can you tell me how to Translate it by my self?
By the way, I can help you translate this plugin into Chinese.
(I just a junior school student, and i can't speak english well. Don't care about my grammar)

**Comment by iamceph** [comment]
Hello, just go here: https://github.com/Misat11/BedWars/new/master/plugin/src/main/resources
and create new language file for chinese. Copy messages_en.yml into it and here we go! :)

**Comment by WangYneos** [comment]
https://github.com/WangYneos/BedWars/blob/master/plugin/src/main/resources/messages_cn.yml
Added

**Comment by Misat11** [comment]
so create pull request

**Comment by WangYneos** [comment]
![屏幕快照 2019-07-31 下午2 43 43](https://user-images.githubusercontent.com/42824603/62189607-fef3ae00-b3a1-11e9-8782-80e763d765f9.png)

**Comment by Misat11** [comment]
click to compare across forks and as head select Misat11/Bedwars master and as compare WangYneos/Bedwars master
