### ISSUE TITLE
Suggestion: Add arenas gui

### ISSUE THREAD

**Issue by FoviOX** [Misat11/BedWars#43]
I suggest add gui for all arenas.
![image](https://user-images.githubusercontent.com/33469628/62129381-3e0cfb00-b2df-11e9-982d-3a38f895af09.png)

**Comment by Bbro122** [comment]
Hey I got something that may be able to help you, my server uses a plugin that can practically make any menu you a thing, with combinations of other plugins  it could easily create it, what it does is allow you to store commands in a item's lore (can be hidden) then placed in the menus you want it, so far its the base to all the things ive needed, though it is outdated its working for me perfectly[https://dev.bukkit.org/projects/createyourownmenus](url) 
Ive been thinking about this as well so I used a plugin called random command to run a random join
command and then I can use a bunch of other items as a join for maps individually, hope this helps

**Comment by iamceph** [comment]
I don't thing this feature is very much needed.
