### ISSUE TITLE
selectteams item disconnect

### ISSUE THREAD

**Issue by WangYneos** [Misat11/BedWars#44]
After i use select teams
i disconnected
![屏幕快照 2019-07-31 上午11 05 59](https://user-images.githubusercontent.com/42824603/62180653-6cdcad00-b383-11e9-916c-f052fc15ba9c.png)

**Comment by WangYneos** [comment]
After i disabled protocolsupportpe
It work well

**Comment by iamceph** [comment]
Names of teams?
