### ISSUE TITLE
Extreme Lag and game starting incorrectly

### ISSUE THREAD

**Issue by FlyFunMan** [Misat11/BedWars#46]
**Describe the bug**
Upon joining the game, I get about one or two frames a second and the council repeatedly reads what I put under "Console Log". If I manage to start the game, the player who started it doesn't get teleported (they keep the lobby items), and the game starts continuously for the other player; they cannot move. The only way to get rid of the lag is to leave the area with the bw match, even if nobody's using it. When started, no resources spawn.

**Server and plugin version**
Spigot version: CraftBukkit version git-Spigot-e6eb36f-d3ed151 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
BedWars version: 0.1.6

**Installed plugins on server (can be obtained by `/pl`):**
VillageGenerator, NametagEdit, DeluxeTags, NoTrashPl, PlaceItemsOnGroundRebuilt, ViaVersion, BSwear, SimpleAPI, CoreProtect, Wild, WorldEdit, AdminFun, NickNames, AutoBroadcast, ArmorStandEditor, MCLib, AdvancedBan, SetSpawn, Votifier, Multiverse-Core, ProtocolLib, MCCore, SimpleGrapple, UberEnchant, CustomStructures, DragonSlayer, iDisguise, LightChatBubbles, SerialKey, TrollCommandsPlusPlus, iDisguiseGui, PermissionsEx, GrapplingHook, BannedWordsPlus, CS-CoreLib, DeepVanish, HolographicDisplays, WorldGuard, Punishmental, Slimefun, Multiverse-NetherPortals, CratesPlus, HubBasics, MobAbilities, SlimeXpansion, Minigames, BuycraftX, Minigames-Regions, SlimefunLuckyBlocks, BKCommonLib, Train_Carts, ReActions, PerWorldInventory, EnchantmentAPI, EnchantmentPack, SkillAPI, Factions, FurnitureLib, DiceFurniture, FurnitureMaker, ProtectionLib, AddLight, Essentials, KitAdder, EssentialsChat, BagOfGold, Vault, ChatPrefixer, GadgetsMenu, BedWars, Carz, DecoHeads, SimplePets, Citizens, CraftBook, SuperVanish, CommandNPC, CrateReloaded
**Console log:**
[21:12:15 WARN]: [BedWars] Task #71079 for BedWars v0.1.6 generated an exception
java.lang.ClassCastException: java.base/java.lang.String cannot be cast to org.bukkit.inventory.ItemStack
        at misat11.bw.game.Game.run(Game.java:1513) ~[?:?]
        at misat11.bw.game.Game$5.run(Game.java:1817) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:392) [spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:889) [spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]
        at java.lang.Thread.run(Unknown Source) [?:?]

**Configuration (of config.yml and shop.yml):**
This is only the config.yml as it's the only thing I changed.

 #Locale (en, cs, ru)
locale: en

allow-crafting: false
keep-inventory-on-death: false
in-lobby-colored-leather-by-team: true
jointeam-entity-show-name: true
friendlyfire: false
player-drops: true
join-randomly-after-lobby-timeout: false
spectator-gm3: false
prevent-killing-villagers: true
compass-enabled: true
join-randomly-on-lobby-join: false
add-wool-to-inventory-on-join: true
prevent-spawning-mobs: true
spawner-holograms: true
spawner-disable-merge: true
prevent-lobby-spawn-mobs-in-radius: 16
spawner-holo-height: 0.25
spawner-holograms-countdown: true
damage-when-player-is-not-in-arena: false
remove-unused-target-blocks: true
allow-block-falling: true

 # Commands whitelist
allowed-commands:
- "/help"

 # Ignored blocks (Farm blocks)
farmBlocks:
  enable: true
  blocks:
  - WHEAT
  - CARROTS
  - POTATOES
  - BEETROOTS

 # Scoreboard settings
scoreboard:
  enable: true
  title: "§a%game%§r - %time%"
  bedLost: "§c\u2718"
  bedExists: "§a\u2714"
  teamTitle: "%bed%%color%%team%"
  
 # Title speed
title:
  fadeIn: 0
  stay: 20
  fadeOut: 0
  
 # Items
items:
  jointeam: COMPASS
  leavegame: SLIME_BALL
  shopback: BARRIER
  shopcosmetic: GRAY_STAINED_GLASS_PANE
  pageback: ARROW
  pageforward: ARROW
  startgame: DIAMOND
  
 # Vault rewards
vault:
  enable: true
  reward:
    kill: 5
    win: 20
  
 # Resources
resources:
  bronze:
    material: BRICK
    interval: 1
    name: "Bronze"
    translate: "resource_bronze"
    color: DARK_RED
    spread: 1.0
  iron:
    material: IRON_INGOT
    interval: 10
    name: "Iron"
    translate: "resource_iron"
    color: GRAY
    spread: 1.0
  gold:
    material: GOLD_INGOT
    interval: 20
    name: "Gold"
    translate: "resource_gold"
    color: GOLD
    spread: 1.0
    
 # Sounds (look to github src/main/java/misat11/bw/utils/Sounds.java for possible values)
sounds:
  on_bed_destroyed: ENTITY_ENDER_DRAGON_GROWL
  on_countdown: UI_BUTTON_CLICK
  on_game_start: ENTITY_PLAYER_LEVELUP
  on_team_kill: ENTITY_PLAYER_DEATH
  on_item_buy: ENTITY_ITEM_PICKUP
  on_upgrade_buy: ENTITY_EXPERIENCE_ORB_PICKUP
  
 # Game effects
game-effects:
  end: 
    type: Firework
    power: 1
    effects:
    - ==: org.bukkit.FireworkEffect
      type: BALL
      fade-colors:
      - ==: org.bukkit.Color
        RED: 255
        GREEN: 255
        BLUE: 255
      colors:
      - ==: org.bukkit.Color
        RED: 255
        GREEN: 255
        BLUE: 255
      trail: false
      flicker: false
  start: {}
  kill: {}
  teamkill: {}
  lobbyjoin: {}
  lobbyleave: {}
  respawn: {}
  beddestroy: {}
  warppowdertick: {}
  
  
 # Lobby scoreboard
lobby-scoreboard:
  enabled: true

  title: "§eBLOCKWARS"
  
  content:
    - " "
    - "§fMap: §2%arena%"
    - "§fPlayers: §2%players%§f/§2%maxplayers%"
    - " "
    - "§fWaiting ..."
    - " "
  
 # Statistics  
statistics:
  enabled: true
  type: 'yaml'
  show-on-game-end: true
  bed-destroyed-kills: false
  
   # Scores configuration
  scores:
    kill: 10
    die: 0
    win: 50
    bed-destroy: 25
    lose: 0
    record: 100
  
 # database (currently only mysql) configuration
database:
  host: localhost
  port: 3306
  db: database
  user: root
  password: secret
  table-prefix: bw_
  
 # Bossbar
bossbar:
  use-xp-bar: false
  lobby:
    enable: true
    color: YELLOW
    style: SEGMENTED_20
  game:
    enable: true
    color: GREEN
    style: SEGMENTED_20
    
 # Holograms
holograms:
   enabled: true  
   headline: "Your §eBLOCKWARS§f stats"
   
 # Chat
chat:
   override: true
   format: "<%teamcolor%%name%§r> "
   separate-game-chat: false
   send-death-messages-just-in-game: true
   default-team-chat-while-running: true
   all-chat-prefix: "@a"
   team-chat-prefix: "@t"
   all-chat: "[ALL] "
   team-chat: "[TEAM] "
   death-chat: "[DEATH] "
   
# Command rewards (possible placeholders {player},{score})
rewards:
   enabled: false
   # Player won
   player-win:
   - /example {player} 200
   # Every player in game
   player-end-game:
   - /example {player} {score}
   # Player destroyed target block of other team
   player-destroy-bed:
   - /example {player} {score}  
   # Player killed other player
   player-kill:
   - /example {player} 10
   
# Give items
game-start-items: true
player-respawn-items: true
gived-game-start-items: [WOODEN_SHOVEL]
gived-player-respawn-items: [WOODEN_SHOVEL]

# Shop lore
lore:
   generate-automatically: true # can be set individual to items
   text:
   - "§7Price:"
   - "§7%price% %resource%"
   - "§7Amount:"
   - "§7%amount%"
   
# Signs (%status% and %players% can be modified in messages_<your language>.yml
sign:
   - "§c§l[BlockWars]"
   - "%arena%"
   - "%status%"
   - "%players%"
   
# Lobby Hotbar (possible values: 0-8, other numbers will disable item)
hotbar: 
   selector: 0
   color: 1
   start: 2
   leave: 8
   
# Do not edit this!!!
version: 2
**If there are problem with only one game, paste here config of this game:**

**Comment by iamceph** [comment]
You have an error in shop.yml.

**Comment by Misat11** [comment]
It could be error in shop.yml but not in this case. Gived start items in config.yml is array of Bukkit's ItemStack, no array of String, so change this line:
```yaml
gived-game-start-items: [WOODEN_SHOVEL]
```
to this:
```yaml
gived-game-start-items: 
- ==: org.bukkit.inventory.ItemStack
  v: 1519
  type: WOODEN_SHOVEL
```
and do same with gived-player-respawn-items

Using Strings here instead of stacks will be added to 0.2.0
