### ISSUE TITLE
Plugin didn't work

### ISSUE THREAD

**Issue by ghost** [Misat11/BedWars#486]
#### Describe the bug
This plugin didn't work, I can't add a game

#### Server and plugin version
Spigot version: 1.19.2 (3610)
BedWars version: 1.3.6

#### Installed plugins on server (can be obtained by `/pl`)
bStats
Music
PluginConstructorAPI
PluginMetrics
SkinsRestorer
WorldEdit
WorldGuard

#### Console log
No

#### Configuration (of config.yml and shop.yml)
NO

#### If there are problem with only one game, paste here config of this game
![2023-06-12_22 25 27](https://github.com/ScreamingSandals/BedWars/assets/120258608/3ff55384-b315-4782-b785-a89d8d684fd5)

**Comment by boiscljo** [comment]
How did you even end up here? This is not BedwarsREL. This is screaming Bedwars, whose version number starts with 0.2.* not 1.3.6, which is a BedwarsREL version. You are not using the correct plugin to submit a bug report on this repository.

**Comment by Misat11** [comment]
Not to mention that BedWarsRel is discontinued and does not support versions above 1.12.2.

Screaming BedWars can be downloaded here: https://www.spigotmc.org/resources/screaming-bedwars-1-8-8-1-20.63714/
