### ISSUE TITLE
Bed don't restoring

### ISSUE THREAD

**Issue by FoviOX** [Misat11/BedWars#49]
**Describe the bug**
(Click on image to see video)
<div align="left">
  <a href="https://www.youtube.com/watch?v=lWr6s_0o9NQ"><img src="https://img.youtube.com/vi/lWr6s_0o9NQ/0.jpg" alt="Click to see video"></a>
</div>

**Server and plugin version**
Spigot version: 1.12.1
BedWars version: 0.1.6

**Console log:**
No errors.

**Configuration (of config.yml and shop.yml):**
Config: https://pastebin.com/GdQqY5DC
Arena: https://pastebin.com/WEVbvRsK

**Comment by Misat11** [comment]
Can you send me your map? (I need it for testing this bug)

**Comment by FoviOX** [comment]
> Can you send me your map? (I need it for testing this bug, because your map is maybe too big and LegacyRegion maybe doesn't count with this)

I have only .schematic - [BeachMap.zip](https://github.com/Misat11/BedWars/files/3471074/BeachMap.zip)

**Comment by Misat11** [comment]
1) Your zip is not working for me
2) About bed isn't restored: I saw you tested it on 1.12.1, what about 1.12.2? Have you any plugins that can modify chunk loading and unloading, for example ClearLag?
3) About wrong color of restored bed: Now I'm solving this issue.

**Comment by FoviOX** [comment]
> 1. Your zip is not working for me

I can upload .schematic on mediafire here link - http://www.mediafire.com/file/7breadb4lma9trc/BeachMap.schematic/file

> 2. About bed isn't restored: I saw you tested it on 1.12.1, what about 1.12.2? Have you any plugins that can modify chunk loading and unloading, for example ClearLag?

I will b test on 1.12.2.
No I don't have ClearLag.
Here all plugins:
![62466065-13b4b500-b799-11e9-9751-38064589990b](https://user-images.githubusercontent.com/33469628/62554457-d3793380-b879-11e9-820e-3680c85ae343.jpg)

> 3. About wrong color of restored bed: Now I'm solving this issue.

Thanks.

**Comment by FoviOX** [comment]
I decided not to test version 1.12.2 because ping too huge:
**1.12.2**
![Screenshot_21](https://user-images.githubusercontent.com/33469628/62557712-2c4bca80-b880-11e9-94f0-d31bb43dc39d.jpg)
**1.12**
![Screenshot_22](https://user-images.githubusercontent.com/33469628/62557724-31107e80-b880-11e9-986b-aff0bec83c1b.jpg)
And I tested version 1.12:
(Click on image to see video)
<div align="left">
  <a href="https://www.youtube.com/watch?v=FlAbSy43QJY"><img src="https://img.youtube.com/vi/FlAbSy43QJY/0.jpg" alt="Click to see video"></a>
</div>

**Comment by Misat11** [comment]
Try latest bedwars build without TickOptimizer plugin

**Comment by FoviOX** [comment]
> Try latest bedwars build without TickOptimizer plugin

Ok I will try.

**Comment by FoviOX** [comment]
On BedWars enabling found error - https://pastebin.com/CPktGVy5

**Comment by Misat11** [comment]
and was this error in 0.1.6 too?

**Comment by FoviOX** [comment]
> and was this error in 0.1.6 too?

No. Only on 0.2.0

**Comment by Misat11** [comment]
I don't understand why MultiWorld is loaded after BedWars instead of before because for me is all working fine. (same version, same multiworld plugin)

**Comment by FoviOX** [comment]
> I don't understand why MultiWorld is loaded after BedWars instead of before because for me it's working fine. (same version, same multiworld plugin)

I writed code who check if world loaded:
https://pastebin.com/3saQRKSX

**Comment by FoviOX** [comment]
> > I don't understand why MultiWorld is loaded after BedWars instead of before because for me it's working fine. (same version, same multiworld plugin)
> 
> I writed code who check if world loaded:
> https://pastebin.com/3saQRKSX

Updated code:
https://pastebin.com/25Zdgv1p

**Comment by Bbro122** [comment]
I took personal interest in this issue and decided to take a look, the issue is fixed im guessing so can you please clarify that its fixed next time, thanks
