### ISSUE TITLE
Things I want to see

### ISSUE THREAD

**Issue by Bbro122** [Misat11/BedWars#50]
- /team support, this is a really great system for me, it would allow me to hook plugins directly onto your plugin using teams that say like <map>-<team> so say I wanted special mobs to not attack a certain team I could use this to simply make another team and make friendly fire off with everyone in it

- commands on join, commands on start, commands on end, this is very useful if I wanted players to do something like auto-remove cosmetics or give them exp for joining games

-  ~~explosion control~~

- player rejoin during a game, if players get kicked during a running game they cant rejoin, I would love it if players could rejoin the game as long as the bed exists, currently, you can only rejoin lobbies

- Command Items, make it where the game can run commands when you buy certain items this is useful for other plugin items that are modified 

- Unexplodable blocks(placed by the player) this is not required and it would be useful

**Comment by iamceph** [comment]
I don't get what do you even mean by this. We have API for this.

**Comment by Bbro122** [comment]
its called feature request because I want features, API does nothing for me if I dont know how to build plugins
