### ISSUE TITLE
Bw Not Saving

### ISSUE THREAD

**Issue by smnootnoot** [Misat11/BedWars#54]
when i try to restart my server after saving my bw game the game dissapears

**Comment by Misat11** [comment]
Any errors in console? have you another plugins? What minecraft version do you have? What bedwars version do you have? Please follow issue templates!

**Comment by smnootnoot** [comment]
im using minecraft version 1.14.4 with BedWars version 0.2.0 for 1.13 + how do you check the console?

**Comment by smnootnoot** [comment]
im using minecraft version 1.14.4 with BedWars version 0.2.0 for 1.13 + how do you check the console
![2019-08-22_11 39 11](https://user-images.githubusercontent.com/54415463/63540740-8334df00-c4d1-11e9-9c40-540e329dc019.png)

**Comment by smnootnoot** [comment]
> Any errors in console? have you another plugins? What minecraft version do you have? What bedwars version do you have? Please follow issue templates!

im using minecraft version 1.14.4 with BedWars version 0.2.0 for 1.13 + how do you check the console
![2019-08-22_11 39 11](https://user-images.githubusercontent.com/54415463/63542104-69e16200-c4d4-11e9-9117-0c0bf64a8e68.png)

**Comment by Misat11** [comment]
Look at server console or latest.log and find something starting with WARN or ERR related to BedWars and send me it with lines below.

**Comment by smnootnoot** [comment]
this issue seems to be happening to hunger games as well when i restart my server it says arena does not exist and if i type /bw admin asionhouse  join  it asion house does not pop up and if i type it in it says this arena does not exist and on the join game signs it says disabled any ideas why this is happening?

**Comment by smnootnoot** [comment]
> Look at server console or latest.log and find something starting with WARN or ERR related to BedWars and send me it with lines below.

found this:
 thread/ERROR]: Error occurred while enabling BedWars v0.2.0 (Is it up to date?)
java.lang.NullPointerException: null

**Comment by Misat11** [comment]
The stack trace has more and more lines, please send me it fully.

**Comment by smnootnoot** [comment]
i think i fixed it by reinstalling and adding the join sign in a different world im testing now

**Comment by smnootnoot** [comment]
ok i fixed it all i hgad to do is add the world with the arena to multiverse thank you for your help!
