### ISSUE TITLE
Only OP

### ISSUE THREAD

**Issue by SkyAcademy** [Misat11/BedWars#55]
Is there a permission to give to users to join a game.
I have a signs but when someone they is not an operator clicks on the sign it does nothing.
Sorry for my bad English if it is.

**Comment by Misat11** [comment]
Move sign out of spawn protection (for example if you have in server.properties set spawn protection to 16, move 34 blocks away from spawn location) or change spawn protection to zero. Non-OP players can't do some things in spawn protection.

**Comment by iamceph** [comment]
Move your signs outside of spawn-protection area or disable it in your server.properties.

**Comment by SkyAcademy** [comment]
Okay, thanks!
