### ISSUE TITLE
BedWars plugin, in Latin Spanish and Spanish Spain

### ISSUE THREAD

**Issue by TooruTNT** [Misat11/BedWars#57]
Hi, I liked how they did the bedwars plugin .. so I took the trouble to translate all the messages for Latin Spanish and Spanish Spain .. I hope you like my translation and my help.. uwu

Atte: TooruTNT 

Translation of Latin Spanish and Spanish Spain
http://www.mediafire.com/file/k1ay1eeyit7alyr/translation.tar/file

**Comment by Misat11** [comment]
Yu should make pull request (copy your filed to directory plugin/src/main/resources)

**Comment by iamceph** [comment]
Thanks, will put it up! :) There will be language update in next version, I will mention you to update it
