### ISSUE TITLE
Protection wall shouldn't have unbreakable blocks

### ISSUE THREAD

**Issue by Pumamori** [Misat11/BedWars#58]
Good day - the protection wall is a great idea, but it spawns unbreakable blocks - it'd be great if we could, if you don't intend to change it, at least have the option to adjust that part of the build, because it effectively makes most games unbeatable, since you can encase your bed in unbreakable blocks.

**Comment by iamceph** [comment]
There is option is config or in shop.yml

**Comment by Pumamori** [comment]
Also, the blocks seem to persist beyond the game - we used them extensively in one game, afterwards, we restarted the server to try a config change and they were still there.  (Only some of them however)

Also, one more question - could you point me towards the change I need to make? I've been toying around with it a lot, but I can't find it, sadly.

**Comment by Pumamori** [comment]
(I forgot to say thank you for the swift reply, my apologies, I'm in a hurry and wanted to respond quick before leaving!)

**Comment by iamceph** [comment]
I will hit you up in hour or so :)

**Comment by Pumamori** [comment]
Thanks! Let me know if you find a solution. (:

**Comment by iamceph** [comment]
**Here you go:**

You got two options: use config.yml config or use (per item) shop.yml settings.
See pictures bellow.

_config.yml:_
![image](https://user-images.githubusercontent.com/4377405/66706277-e8b68680-ed30-11e9-9a80-83c0ae9ab388.png)


_shop.yml:_
![image](https://user-images.githubusercontent.com/4377405/66706286-fe2bb080-ed30-11e9-8f07-9403ae463677.png)

**Comment by Pumamori** [comment]
Thank you very much!
