### ISSUE TITLE
the scoreboard is not displayed on spigot 1.13.2

### ISSUE THREAD

**Issue by Guest1131** [Misat11/BedWars#9]
I found a problem, the scoreboard is not displayed on spigot 1.13.2

**Comment by Misat11** [comment]
And have you enabled scoreboard in your config? Or do you have any other plugin that can works with scoreboard?

**Comment by Guest1131** [comment]
Yes, I activated the scoreboard in the config, and I don't use another plugin.

How do I do that?

I have spigot 1.13.2

**Comment by Chicken009** [comment]
"and I don't use another plugin"

You need this Plugin if you want the scoreboards to show up:

https://dev.bukkit.org/projects/holographic-displays
